include:
  - project: "platform/base/pipeline"
    ref: master
    file:
      - "template.gitlab-ci.yml"

stages:
  - build
  - check
  - publish-msg
  - deploy
  - announcement

build:
  stage: build
  image: registry.trendyol.com/mobile/mobile-all/android-all/platform-subgroup/image/android-sdk:8.8.0-jdk17-34.0.0-26.1.10909125-34-8f657213
  script:
    - gradle assemble
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always

check:
  stage: check
  image: registry.trendyol.com/mobile/mobile-all/android-all/platform-subgroup/image/android-sdk:8.8.0-jdk17-34.0.0-26.1.10909125-34-8f657213
  script:
    - gradle check
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always

publish-msg:
  stage: publish-msg
  image: python:3.6
  variables:
    PUBLISH_MSG_DESCRIPTION: "default publish message"
  script:
    - python3 ./scripts/publish_message_description.py
    - 'curl -X POST "https://leylek.trendyol.com/slack/send-message" --header "Content-Type: application/json" --header "Authorization: 442c5be1-5fa8-4880-b304-619eebb61d65" --data-raw "{ \"channel\": \"temp-leylek-commands-workflow\", \"message\": \"$PUBLISH_MSG_DESCRIPTION\" }"'

publish:
  stage: deploy
  image: registry.trendyol.com/mobile/mobile-all/android-all/platform-subgroup/image/android-sdk:8.8.0-jdk17-34.0.0-26.1.10909125-34-8f657213
  script:
    - gradle publishReleasePublicationToNexusRepository
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - gradle/published-libs.versions.toml

announce:
  stage: deploy
  variables:
    PUBLISH_MSG_DESCRIPTION: "default publish message"
  needs: [ "publish" ]
  script:
    - python3 ./scripts/publish_message_description.py
    - 'export PUBLISH_MSG="UI Kit new version deployed. :checkmark:\nDeployer: $GITLAB_USER_NAME\nImage Tag: $CI_COMMIT_REF_NAME\nDescription: $PUBLISH_MSG_DESCRIPTION"'
    - 'curl -X POST "https://leylek.trendyol.com/slack/send-message" --header "Content-Type: application/json" --header "Authorization: 442c5be1-5fa8-4880-b304-619eebb61d65" --data-raw "{ \"channel\": \"android-ui-kit\", \"message\": \"$PUBLISH_MSG\" }"'
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - gradle/published-libs.versions.toml
