include:
  - project: "platform/base/pipeline"
    ref: master
    file:
      - "template.gitlab-ci.yml"

stages:
  - build
  - check
  - setup
  - publish-msg
  - deploy
  - announcement

variables:
  VIRTUAL_ENV: "venv"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

build:
  stage: build
  image: registry.trendyol.com/mobile/mobile-all/android-all/platform-subgroup/image/android-sdk:8.8.0-jdk17-34.0.0-26.1.10909125-34-8f657213
  script:
    - gradle assemble
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always

check:
  stage: check
  image: registry.trendyol.com/mobile/mobile-all/android-all/platform-subgroup/image/android-sdk:8.8.0-jdk17-34.0.0-26.1.10909125-34-8f657213
  script:
    - gradle check
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always

setup:
  stage: setup
  image: python:3.6
  script:
    - python3 -m venv $VIRTUAL_ENV
    - source $VIRTUAL_ENV/bin/activate
    - pip install --upgrade pip
    - pip install -r ./scripts/requirements.txt
  artifacts:
    paths:
      - venv/

publish-msg:
  stage: publish-msg
  image: python:3.6
  script:
    - source venv/bin/activate
    - python3 ./scripts/publish_message_description.py
  dependencies:
    - setup

publish:
  stage: deploy
  image: registry.trendyol.com/mobile/mobile-all/android-all/platform-subgroup/image/android-sdk:8.8.0-jdk17-34.0.0-26.1.10909125-34-8f657213
  script:
    - gradle publishReleasePublicationToNexusRepository
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - gradle/published-libs.versions.toml

announce:
  stage: deploy
  image: python:3.6
  needs: [ "publish", "setup" ]
  script:
    - source venv/bin/activate
    - python3 ./scripts/publish_message_description.py
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - gradle/published-libs.versions.toml
