include:
  - project: "platform/base/pipeline"
    ref: master
    file:
      - "template.gitlab-ci.yml"

stages:
  - analysis
  - build
  - publish
  - announcement

detekt:
  stage: analysis
  image: registry.trendyol.com/mobile/mobile-all/android-all/platform-subgroup/image/android-sdk:8.8.0-jdk17-34.0.0-26.1.10909125-34-8f657213
  script:
    - gradle detekt

build:
  stage: build
  image: registry.trendyol.com/mobile/mobile-all/android-all/platform-subgroup/image/android-sdk:8.8.0-jdk17-34.0.0-26.1.10909125-34-8f657213
  script:
    - gradle assemble

publish:
  stage: publish
  image: registry.trendyol.com/mobile/mobile-all/android-all/platform-subgroup/image/android-sdk:8.8.0-jdk17-34.0.0-26.1.10909125-34-8f657213
  variables:
    VERSION: ${CI_COMMIT_REF_NAME}
  script:
    - gradle publishReleasePublicationToNexusRepository
  only:
    - tags

announcement:
  stage: announcement
  script:
    - 'export PUBLISH_MSG="UI Kit new version deployed. :checkmark:\nDeployer: $GITLAB_USER_NAME\nImage Tag: $CI_COMMIT_REF_NAME\nDescription: $CI_RELEASE_DESCRIPTION"'
    - 'curl -X POST "https://leylek.trendyol.com/slack/send-message" --header "Content-Type: application/json" --header "Authorization: 442c5be1-5fa8-4880-b304-619eebb61d65" --data-raw "{ \"channel\": \"android-ui-kit\", \"message\": \"$PUBLISH_MSG\" }"'
  only:
    - tags
