include:
  - project: "platform/base/pipeline"
    ref: master
    file:
      - "template.gitlab-ci.yml"

stages:
  - build
  - publish

build:
  stage: build
  image: registry.trendyol.com/mobile/mobile-all/android-all/platform-subgroup/image/android-sdk:8.4.0-jdk17-34.0.0-25.1.8937393-34-0db92d1b
  script:
    - gradle assemble

publish:
  stage: publish
  image: registry.trendyol.com/mobile/mobile-all/android-all/platform-subgroup/image/android-sdk:8.4.0-jdk17-34.0.0-25.1.8937393-34-0db92d1b
  variables:
    VERSION: ${CI_COMMIT_REF_NAME}
  script:
    - gradle publishReleasePublicationToNexusRepository
  only:
    - tags
