package com.trendyol.design.ui.component.common

object Component {

    const val HEADER = "Header"
    const val TITLE = "Title"
    const val SUBTITLE = "Subtitle"
    const val BODY1 = "Body1"
    const val BODY2 = "Body2"
    const val OVERLINE = "Overline"

    const val PRIMARY_BUTTON = "Primary"
    const val SECONDARY_BUTTON = "Secondary"
    const val TERTIARY_BUTTON = "Tertiary"

    const val ARROW_DOWN_ICON = "ArrowDown"
    const val BASKET_ICON = "Basket"
    const val BULLET_ICON = "Bullet"
    const val CAMPAIGN_ICON = "Campaign"
    const val CAMPAIGN_DOWN_ARROW_ICON = "CampaignDownArrow"
    const val CANCEL_ICON = "Cancel"
    const val CARGO_ICON = "Cargo"
    const val CIRCLE_ICON = "CircleIcon"
    const val COLON_ICON = "Colon"
    const val COUPON_ICON = "Coupon"
    const val CREDIT_ICON = "Credit"
    const val DELIVERY_ICON = "Delivery"
    const val FAVORITE_SELECTED_ICON = "FavoriteSelected"
    const val FENOMEN_GRADIENT_ICON = "FenomenGradient"
    const val HELP_ICON = "Help"
    const val INFO_ICON = "InfoIcon"
    const val PAUSE_BUTTON_ICON = "PauseButton"
    const val PERCENTAGE_ICON = "Percentage"
    const val PLAY_BUTTON_ICON = "PlayButton"
    const val PLAY_GRADIENT_ICON = "PlayGradient"
    const val RUNNING_OUT_ICON = "RunningOut"
    const val SAVE_SELECTED_ICON = "SaveSelected"
    const val SEARCH_ICON = "Search"
    const val SHARE_ICON = "Share"
    const val STAR_ICON = "Star"
    const val STATE_ORDER_ICON = "StateOrder"
    const val STATE_PIN_ICON = "StatePin"
    const val STATE_REFRESH_ICON = "StateRefresh"
    const val TICK_ICON = "Tick"
    const val TRASH_ICON = "Trash"
    const val WARNING_INFO_DEFAULT_ICON = "WarningInfoDefault"
    const val BACK_ICON = "Back"
    const val CHEVRON_ICON = "Chevron"
    const val ERROR_STATE_ICON = "ErrorState"
    const val FAVORITE_UNSELECTED_ICON = "FavoriteUnselected"
    const val SAVE_UNSELECTED = "SaveUnselected"
    const val STATE_CAUTION_ICON = "StateCaution"
    const val SUCCESS_STATE_ICON = "SuccessState"
    const val UNION_ICON = "Union"

    const val NO_BUTTON = "No Button"
    const val SINGLE_BUTTON = "Single Button"
    const val TWO_BUTTON = "Two Button"

    const val TOOLBAR_NONE = "ToolbarNone"
    const val TOOLBAR_TEXT_BUTTON = "ToolbarTextButton"
    const val TOOLBAR_END_ICON = "ToolbarEndIcon"
    const val TOOLBAR_END_TWO_ICON = "ToolbarEndTwoIcon"
    const val TOOLBAR_ICON_NONE = "ToolbarIconNone"
    const val TOOLBAR_ICON_TEXT_BUTTON = "ToolbarIconTextButton"
    const val TOOLBAR_ICON_END_ICON = "ToolbarIconEndIcon"
    const val TOOLBAR_ICON_END_TWO_ICON = "ToolbarIconEndTwoIcon"

    const val HORIZONTAL_LOADING = "HorizontalLoading"
    const val CIRCULAR_LOADING = "CircularLoading"

    const val RADIO_BUTTON_NONE = "None"
    const val RADIO_BUTTON_TEXT = "Text"
    const val RADIO_BUTTON_CONTENT = "Content"

    const val INPUT_FIELD_SINGLE_LINE = "SingleLine"
    const val INPUT_FIELD_MULTI_LINE = "MultiLine"
    const val INPUT_FIELD_DROPDOWN = "Dropdown"
    const val INPUT_FIELD_EMAIL = "Email"
    const val INPUT_FIELD_PHONE_NUMBER = "PhoneNumber"
    const val INPUT_FIELD_PASSWORD = "Password"
    const val INPUT_FIELD_OTP = "OTP"
    const val INPUT_FIELD_SEARCH_BAR = "SearchBar"

    const val CHECKBOX_NONE = "None"
    const val CHECKBOX_TEXT = "Text"
    const val CHECKBOX_CONTENT = "Content"

    const val BOTTOM_SHEET_LIST = "BottomSheetListContent"
    const val BOTTOM_SHEET_SLIDER = "BottomSheetSliderContent"
    const val BOTTOM_SHEET_IMAGE = "BottomSheetImageContent"

    const val BOTTOM_SHEET_HEADER = "BottomSheetHeader"

    const val LIST_CELL_RADIO_ITEM = "BottomSheetRadioItem"
    const val LIST_CELL_CHECKBOX_ITEM = "BottomSheetCheckboxItem"
    const val LIST_CELL_SINGLE_SELECT_ITEM = "BottomSheetSingleSelectItem"
    const val LIST_CELL_STATIC_ITEM = "BottomSheetStaticItem"

    const val RATING_BAR = "Rating Bar"

    const val COUNTDOWN_TIMER = "Countdown Timer"

    const val BOX_BADGE_CUSTOM = "Custom"
    const val BOX_BADGE_COUPON = "Coupon"
    const val BOX_BADGE_FREE_DELIVERY = "FreeDelivery"
    const val BOX_BADGE_FAST_DELIVERY = "FastDelivery"
    const val BOX_BADGE_BUY_MORE_PAY_LESS = "BuyMorePayLess"
    const val BOX_BADGE_BUY_TOGETHER = "BuyTogether"
    const val BOX_BADGE_VIDEO = "Video"
    const val BOX_BADGE_TODAY_DELIVERY = "TodayDelivery"
    const val BOX_BADGE_CREDIT = "Credit"
    const val BOX_BADGE_INFLUENCER_CHOICE = "InfluencerChoice"

    const val BOX_BADGE_GROUP_4_ITEM = "4ItemsBoxBadgeGroup"
    const val BOX_BADGE_GROUP_3_ITEM = "3ItemsBoxBadgeGroup"
    const val BOX_BADGE_GROUP_2_ITEM = "2ItemsBoxBadgeGroup"
    const val BOX_BADGE_GROUP_1_ITEM = "1ItemsBoxBadgeGroup"

    const val PRICE_SINGLE = "Single Price"
    const val PRICE_DUAL = "Dual Price"

    const val ALERT_DIALOG = "Native Alert Dialog"
    const val SUCCESS_DIALOG = "Success Dialog"
    const val ERROR_DIALOG = "Error Dialog"
    const val GENERIC_DIALOG = "Generic Dialog"

    const val INFO_BOX_LEFT_ICON = "Info Box Left Icon"
    const val INFO_BOX_RIGHT_ICON = "Info Box Right Icon"
    const val INFO_BOX_NO_ICON = "Info Box No Icon"

    const val STANDARD_ICON_BUTTON = "Standard Icon Button"
    const val CONTAINED_ICON_BUTTON = "Contained Icon Button"
}
