# This is a basic workflow to help you get started with Actions

name: Komposto CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  shot:
    runs-on: macos-13
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 32
          arch: 'arm64-v8a'
          profile: 'pixel_6'
          avd-name: ubuntu-avd-arm64-v8a-32
          script: ./gradlew executeScreenshotTests
          
#      - name: Upload Screenshot Test Results
#        if: failure()
#        uses: actions/upload-artifact@v4
#        with:
#          name: screenshot-test-results
#          path: |
#            app/screenshots/debug/
#            app/build/tmp/shot/screenshot/
#            app/build/reports/shot/debug/verification/
#          retention-days: 1
          
      - name: Send success message to Slack
        if: success()
        uses: slackapi/slack-github-action@v2.1.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_DEV_CHANNEL_ID }}
            text: "✅ Screenshot tests completed successfully! \nPipeline: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            
      - name: Send failure message to Slack
        if: failure()
        uses: slackapi/slack-github-action@v2.1.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_DEV_CHANNEL_ID }}
            text: "❌ Screenshot tests failed! \nPipeline: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"