name: Screenshot & Interaction Tests

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  screenshot-and-interaction-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full git history for comparing changes
          ref: ${{ github.event.pull_request.head.ref }}  # Checkout the PR branch (not merge commit)
          repository: ${{ github.event.pull_request.head.repo.full_name }}  # Checkout from fork if needed
          token: ${{ secrets.GITHUB_TOKEN }}  # Need a token with push permissions
          lfs: true  # Pull Git LFS files (screenshots are stored in LFS)

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-32

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 32
          arch: x86_64
          profile: pixel_6
          target: google_apis
          avd-name: ubuntu-avd-x86_64-32
          emulator-boot-timeout: 120
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Run screenshot tests
        id: run_screenshot_tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 32
          arch: x86_64
          profile: pixel_6
          target: google_apis
          avd-name: ubuntu-avd-x86_64-32
          emulator-boot-timeout: 120
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew executeScreenshotTests
        continue-on-error: true

      - name: Run interaction tests
        id: run_interaction_tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 32
          arch: x86_64
          profile: pixel_6
          target: google_apis
          avd-name: ubuntu-avd-x86_64-32
          emulator-boot-timeout: 120
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew :app:connectedDebugAndroidTest -Pandroid.testInstrumentationRunnerArguments.annotation=core.InteractionTest

      - name: Clear screenshots and record new ones
        if: steps.run_screenshot_tests.outcome == 'failure'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 32
          arch: x86_64
          profile: pixel_6
          target: google_apis
          avd-name: ubuntu-avd-x86_64-32
          emulator-boot-timeout: 120
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            rm -rf app/screenshots/debug/
            ./gradlew executeScreenshotTests -Precord

      - name: Commit new screenshots
        if: steps.run_screenshot_tests.outcome == 'failure' && github.event.pull_request.head.repo.full_name == github.repository
        run: |
          git config --local user.email "ci@github.actions.com"
          git config --local user.name "GitHub Actions"
          git add app/screenshots/debug/
          git commit -m "Update screenshots from CI" || echo "No changes to commit"
          git push

      - name: Comment on fork PR about screenshots
        if: steps.run_screenshot_tests.outcome == 'failure' && github.event.pull_request.head.repo.full_name != github.repository
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '📸 Screenshot tests detected differences!\n\n' +
                    '## Option 1: Update screenshots automatically in your fork (Recommended)\n' +
                    '1. Go to the **Actions** tab in your fork\n' +
                    '2. Select **"Update Screenshots (For Forks)"** workflow\n' +
                    '3. Click **"Run workflow"** and select your branch (`' + context.payload.pull_request.head.ref + '`)\n' +
                    '4. Wait for the workflow to complete - screenshots will be committed automatically\n' +
                    '5. Your PR will be updated with the new screenshots\n\n' +
                    '## Option 2: Manual download\n' +
                    '1. Download the `screenshot-test-results` artifact from this workflow run\n' +
                    '2. Extract `app/screenshots/debug/` to your local repository\n' +
                    '3. Commit and push the updated screenshots\n\n' +
                    '**Note:** Screenshots must be generated on CI to ensure consistency across different platforms.'
            })

      - name: Upload Screenshot Test Results
        if: steps.run_screenshot_tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-test-results
          path: |
            app/screenshots/debug/
            app/build/tmp/shot/screenshot/
            app/build/reports/shot/debug/verification/
          retention-days: 7

      - name: Upload Interaction Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: interaction-test-results
          path: |
            app/build/outputs/androidTest-results/connected/
            app/build/reports/androidTests/connected/
          retention-days: 7
