name: Screenshot Test

on:
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  screenshot-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full git history for comparing changes
          token: ${{ secrets.GITHUB_TOKEN }}  # Need a token with push permissions

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-32

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 32
          arch: x86_64
          profile: pixel_6
          target: google_apis
          avd-name: ubuntu-avd-x86_64-32
          emulator-boot-timeout: 120
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Run screenshot tests
        id: run_tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 32
          arch: x86_64
          profile: pixel_6
          target: google_apis
          avd-name: ubuntu-avd-x86_64-32
          emulator-boot-timeout: 120
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew executeScreenshotTests
        continue-on-error: true

      - name: Clear screenshots and record new ones
        if: steps.run_tests.outcome == 'failure'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 32
          arch: x86_64
          profile: pixel_6
          target: google_apis
          avd-name: ubuntu-avd-x86_64-32
          emulator-boot-timeout: 120
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            rm -rf app/screenshots/debug/
            ./gradlew executeScreenshotTests -Precord

      - name: Commit new screenshots
        if: steps.run_tests.outcome == 'failure' && github.event_name == 'pull_request'
        run: |
          git config --local user.email "ci@github.actions.com"
          git config --local user.name "GitHub Actions"
          git add app/screenshots/debug/
          git commit -m "Update screenshots from CI" || echo "No changes to commit"
          git push

      - name: Upload Screenshot Test Results
        if: steps.run_tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-test-results
          path: |
            app/screenshots/debug/
            app/build/tmp/shot/screenshot/
            app/build/reports/shot/debug/verification/
          retention-days: 1
